# .github/workflows/deploy-remote.yml
name: Deploy Hugo site to Remote Server

on:
  # 当推送到main分支时触发
  push:
    branches:
      - main

  # 允许手动触发工作流
  workflow_dispatch:

# 默认使用bash
defaults:
  run:
    shell: bash

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.147.8

    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ secrets.SITE_URL }}"

      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # 创建备份目录（可选）
            if [ -d "${{ secrets.DEPLOY_PATH }}" ]; then
              sudo cp -r ${{ secrets.DEPLOY_PATH }} ${{ secrets.DEPLOY_PATH }}.backup.$(date +%Y%m%d_%H%M%S)
            fi

            # 清空目标目录
            sudo rm -rf ${{ secrets.DEPLOY_PATH }}/*

            # 创建目标目录（如果不存在）
            sudo mkdir -p ${{ secrets.DEPLOY_PATH }}

      - name: Copy files to Remote Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "public/*"
          target: ${{ secrets.DEPLOY_PATH }}
          strip_components: 1

      - name: Set permissions and restart services
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # 设置正确的文件权限
            # sudo chown -R www-data:www-data ${{ secrets.DEPLOY_PATH }}
            sudo chmod -R 755 ${{ secrets.DEPLOY_PATH }}

            # 重启Nginx（可选，根据你的服务器配置）
            sudo systemctl reload nginx

            echo "部署完成！"
